# Generated by Django 5.2.8 on 2025-11-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='tipo',
            field=models.CharField(choices=[('movie', 'Pelicula'), ('series', 'Serie')], default='movie', max_length=10),
        ),
    ]
