# Generated by Django 5.2.8 on 2025-11-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pelicula_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
